apiVersion: v1
kind: Secret
metadata:
  name: medflow-secret
  namespace: medflow
type: Opaque
stringData:
  DATABASE_PASSWORD: "root"
  DATABASE_USER: "root"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: medflow-config
  namespace: medflow
data:
  DEBUG: "True"
  DATABASE_NAME: "medflowdb"
  DATABASE_HOST: "medflow-db"
  DATABASE_PORT: "5432"
  DATABASE_USER: "root"
  DATABASE_PASSWORD: "root"
  BACKEND_HOST: "medflow-backend"
  BACKEND_PORT: "8000"
  ALLOWED_HOSTS: "*"
  POSTGRES_PASSWORD: "root"
  POSTGRES_USER: "root"
  POSTGRES_DB: "medflowdb"
  BACKEND_URL: "http://medflow-backend:8000/api/"
  NEXTAUTH_URL: "http://localhost:3000"
  NEXTAUTH_SECRET: "zvjZ+JGJZR2A1Hxxwwc2k5Td75QLlKw8+wKvUSYqAjs="
